name: Auto-update firmware

on:
  schedule:
    # daily, hour and minute chosen arbitrarily
    - cron: "32 14 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Download latest firmware files from https://archive.raspberrypi.org/debian/
        id: download
        run: |
          # split lines to fail on exit != 0
          version="$(go run ./cmd/retrieve/main.go)"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Commit the new firmware
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: firmware ${{steps.download.outputs.version}}
          tagging_message: v1.0.0-${{steps.download.outputs.version}}

      - name: Add blank commit every 55 days to keep cron alive
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          time_elapsed: 55
