name: Auto-update firmware

on:
  schedule:
    # daily, hour and minute chosen arbitrarily
    - cron: "32 14 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Download latest firmware files from https://archive.raspberrypi.org/debian/
        id: download
        run: |
          # split lines to fail on exit != 0
          version="$(go run ./cmd/retrieve/main.go)"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if last commit happened long ago
        id: date_check
        run: |
          current_timestamp=$(date -d "now" +%s)
          commit_timestamp=$(git log -1 --format=%ct)
          difference_seconds=$((current_timestamp - commit_timestamp))
          difference_days=$((difference_seconds / (60)))
          if [[ $difference_days -gt 2 ]]; then
            echo "flag= --allow-empty" >> "$GITHUB_OUTPUT"
          else
            echo "flag=" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit the new firmware
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: firmware ${{steps.download.outputs.version}}
          tagging_message: v1.0.0-${{steps.download.outputs.version}}
          skip_dirty_check: ${{ contains(steps.date_check.outputs.flag, '--') }} # only when --allow-empty is added below
          commit_options: ${{steps.date_check.outputs.flag}}
