name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Download latest firmware version from https://archive.raspberrypi.org/debian/
      id: download
      run: echo "::set-output version=$(go run ./cmd/retrieve/main.go)"
    - name: echo
      run: echo ${{steps.download.version}}

