name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Download latest firmware files from https://archive.raspberrypi.org/debian/
      id: download
      run: echo "::set-output name=version::$(go run ./cmd/retrieve/main.go)"
      
      
    - name: Commit the new firmware
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: firmware ${{steps.download.outputs.version}}
